# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

before:
  hooks:
    - make gen
    - go mod tidy

builds:
  - id: coffee-table-server
    env:
      - CGO_ENABLED=0
    main: ./cmd/server
    binary: coffee-table-server
    goos:
      - linux
      - windows
      - darwin
  - id: coffee-table
    env:
      - CGO_ENABLED=0
    main: ./cmd/client
    binary: coffee-table
    goos:
      - linux
      - windows
      - darwin

archives:
  - formats: [tar.gz]
    name_template: >-
      {{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ .Arm }}
    format_overrides:
      - goos: windows
        formats: [zip]

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
